blueprint:
  name: Sanftes Aufwachlicht (Ultimate)
  description: Simuliert einen Sonnenaufgang. Unterstuetzt 2 Zeitplaene, Handy-Wecker, Anwesenheit und Farbtemperatur-Verlauf.
  domain: automation
  input:
    target_light:
      name: Licht
      selector:
        entity:
          domain: light
    
    # Farbtemperatur Verlauf
    start_light_color:
      name: Start-Farbtemperatur
      description: Lichtfarbe zu Beginn (Dunkelrot/Warm).
      default: "Warmest (500 mired)"
      selector:
        select:
          options:
            - "Coolest (142 mired)"
            - "Cool (4000K)"
            - "Neutral (2700K)"
            - "Warm (2200K)"
            - "Warmest (500 mired)"
    end_light_color:
      name: End-Farbtemperatur
      description: Lichtfarbe am Ende (Hell/Neutral). Waehle dieselbe Farbe wie Start fuer 'Fix', oder eine andere fuer einen Verlauf.
      default: "Neutral (2700K)"
      selector:
        select:
          options:
            - "Coolest (142 mired)"
            - "Cool (4000K)"
            - "Neutral (2700K)"
            - "Warm (2200K)"
            - "Warmest (500 mired)"

    duration:
      name: Dauer (Sekunden)
      default: 300
      selector:
        number:
          min: 60
          max: 3600
          unit_of_measurement: seconds
    
    # Profil 1
    trigger_time_1:
      name: Startzeit 1 (z.B. Werktags)
      default: "06:30:00"
      selector:
        time: {}
    days_1:
      name: Tage für Startzeit 1
      default: [mon, tue, wed, thu, fri]
      selector:
        select:
          multiple: true
          options:
            - {label: Montag, value: mon}
            - {label: Dienstag, value: tue}
            - {label: Mittwoch, value: wed}
            - {label: Donnerstag, value: thu}
            - {label: Freitag, value: fri}
            - {label: Samstag, value: sat}
            - {label: Sonntag, value: sun}

    # Profil 2
    trigger_time_2:
      name: Startzeit 2 (z.B. Wochenende)
      default: "09:00:00"
      selector:
        time: {}
    days_2:
      name: Tage für Startzeit 2
      default: [sat, sun]
      selector:
        select:
          multiple: true
          options:
            - {label: Montag, value: mon}
            - {label: Dienstag, value: tue}
            - {label: Mittwoch, value: wed}
            - {label: Donnerstag, value: thu}
            - {label: Freitag, value: fri}
            - {label: Samstag, value: sat}
            - {label: Sonntag, value: sun}

    # Handy Wecker
    alarm_sensor:
      name: Handy Wecker Sensor (Optional)
      description: Waehle den 'Next Alarm' Sensor.
      default: none
      selector:
        entity:
          domain: sensor
          device_class: timestamp

    # Anwesenheit
    presence_sensor:
      name: Anwesenheits-Sensor (Optional)
      description: "Trigger nur, wenn dieser Sensor auf 'home' steht. Leer lassen für 'immer'."
      default: none
      selector:
        entity:
          domain: [person, device_tracker]

variables:
  total_duration: !input duration
  delay_seconds: "{{ total_duration | float / 50 }}"
  
  # Input Variablen fuer Farben
  var_start_color: !input start_light_color
  var_end_color: !input end_light_color

  # Hilfsfunktion zur Mired Berechnung (Logik verdoppelt da Macro in Blueprint schwierig)
  start_mireds: >
    {% if var_start_color == 'Coolest (142 mired)' %} 142
    {% elif var_start_color == 'Cool (4000K)' %} 250
    {% elif var_start_color == 'Neutral (2700K)' %} 370
    {% elif var_start_color == 'Warm (2200K)' %} 454
    {% else %} 500 {% endif %}

  end_mireds: >
    {% if var_end_color == 'Coolest (142 mired)' %} 142
    {% elif var_end_color == 'Cool (4000K)' %} 250
    {% elif var_end_color == 'Neutral (2700K)' %} 370
    {% elif var_end_color == 'Warm (2200K)' %} 454
    {% else %} 500 {% endif %}

  # Schrittweite berechnen
  mired_step: "{{ (end_mireds | int - start_mireds | int) / 50 }}"

  # Weitere Variablen
  var_alarm_sensor: !input alarm_sensor
  var_duration_seconds: !input duration
  var_presence_sensor: !input presence_sensor

trigger:
  - platform: time
    at: !input trigger_time_1
    id: "t1"
  - platform: time
    at: !input trigger_time_2
    id: "t2"
  - platform: template
    value_template: >
      {% if var_alarm_sensor != none %}
        {% set alarm_state = states(var_alarm_sensor) %}
        {% if alarm_state not in ['unknown', 'unavailable', 'None'] %}
          {% set alarm_ts = as_timestamp(alarm_state) %}
          {% if alarm_ts %}
             {% set start_ts = alarm_ts - var_duration_seconds | int %}
             {% set now_ts = as_timestamp(now()) %}
             {{ now_ts >= start_ts and now_ts < (start_ts + 60) }}
          {% endif %}
        {% endif %}
      {% endif %}
    id: "t_alarm"

condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: trigger
            id: "t1"
          - condition: time
            weekday: !input days_1
      - condition: and
        conditions:
          - condition: trigger
            id: "t2"
          - condition: time
            weekday: !input days_2
      - condition: and
        conditions:
          - condition: trigger
            id: "t_alarm"
          - condition: template
            value_template: >
              {% if var_presence_sensor == none %} true
              {% else %} {{ is_state(var_presence_sensor, 'home') }}
              {% endif %}

action:
  # Start: Licht einschalten (Start-Farbe)
  - service: light.turn_on
    target: {entity_id: !input target_light}
    data:
      brightness_pct: 1
      color_temp: "{{ start_mireds | int }}"
      transition: 0
  
  # Schleife mit Farbverlauf
  - repeat:
      count: 50
      sequence:
        - delay: {seconds: "{{ delay_seconds }}"}
        - service: light.turn_on
          target: {entity_id: !input target_light}
          data:
            brightness_pct: "{{ repeat.index * 2 }}"
            # Berechne aktuelle Farbe: Start + (Index * Step)
            color_temp: "{{ (start_mireds | int + (mired_step | float * repeat.index)) | int }}"
            transition: 0
