blueprint:
  name: Sanftes Aufwachlicht (Schrittweise + Farbe)
  description: Dimmt ein beliebiges Licht schrittweise hoch und setzt die gewuenschte Farbtemperatur (unterstuetzt Mireds & Kelvin).
  domain: automation
  input:
    trigger_time:
      name: Startzeit
      selector:
        time: {}
    on_days:
      name: Wochentage
      description: An welchen Tagen soll der Wecker aktiv sein?
      default: 
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      selector:
        select:
          multiple: true
          options:
            - label: Montag
              value: mon
            - label: Dienstag
              value: tue
            - label: Mittwoch
              value: wed
            - label: Donnerstag
              value: thu
            - label: Freitag
              value: fri
            - label: Samstag
              value: sat
            - label: Sonntag
              value: sun
    target_light:
      name: Licht
      selector:
        entity:
          domain: light
    light_color:
      name: Farbtemperatur
      description: Waehle die gewuenschte Lichtfarbe (angepasst an deine Lampe).
      default: "Neutral (2700K)"
      selector:
        select:
          options:
            - "Coolest (142 mired)"
            - "Cool (4000K)"
            - "Neutral (2700K)"
            - "Warm (2200K)"
            - "Warmest (500 mired)"
    duration:
      name: Dauer (Sekunden)
      description: Gesamtdauer des Dimmvorgangs.
      default: 300
      selector:
        number:
          min: 60
          max: 3600
          unit_of_measurement: seconds

variables:
  total_duration: !input duration
  delay_seconds: "{{ total_duration | float / 50 }}"
  selected_color: !input light_color
  # Umrechnung in Mireds (Home Assistant Standard)
  target_mireds: >
    {% if selected_color == 'Coolest (142 mired)' %}
      142
    {% elif selected_color == 'Cool (4000K)' %}
      250
    {% elif selected_color == 'Neutral (2700K)' %}
      370
    {% elif selected_color == 'Warm (2200K)' %}
      454
    {% else %}
      500
    {% endif %}

trigger:
  - platform: time
    at: !input trigger_time

condition:
  - condition: time
    weekday: !input on_days

action:
  # Start: Licht einschalten
  - service: light.turn_on
    target:
      entity_id: !input target_light
    data:
      brightness_pct: 1
      color_temp: "{{ target_mireds }}"
      transition: 0

  # Schleife
  - repeat:
      count: 50
      sequence:
        - delay:
            seconds: "{{ delay_seconds }}"
        - service: light.turn_on
          target:
            entity_id: !input target_light
          data:
            brightness_pct: "{{ repeat.index * 2 }}"
            color_temp: "{{ target_mireds }}"
            transition: 0
