blueprint:
  name: Sanftes Aufwachlicht (Dual-Profil)
  description: Dimmt ein Licht schrittweise hoch. Unterstuetzt zwei separate Zeitplaene (z.B. Werktags vs. Wochenende).
  domain: automation
  input:
    target_light:
      name: Licht
      selector:
        entity:
          domain: light
    light_color:
      name: Farbtemperatur
      description: Waehle die gewuenschte Lichtfarbe.
      default: "Neutral (2700K)"
      selector:
        select:
          options:
            - "Coolest (142 mired)"
            - "Cool (4000K)"
            - "Neutral (2700K)"
            - "Warm (2200K)"
            - "Warmest (500 mired)"
    duration:
      name: Dauer (Sekunden)
      default: 300
      selector:
        number:
          min: 60
          max: 3600
          unit_of_measurement: seconds
    
    # Profil 1
    trigger_time_1:
      name: Startzeit 1 (z.B. Werktags)
      default: "06:30:00"
      selector:
        time: {}
    days_1:
      name: Tage für Startzeit 1
      default: 
        - mon
        - tue
        - wed
        - thu
        - fri
      selector:
        select:
          multiple: true
          options:
            - label: Montag
              value: mon
            - label: Dienstag
              value: tue
            - label: Mittwoch
              value: wed
            - label: Donnerstag
              value: thu
            - label: Freitag
              value: fri
            - label: Samstag
              value: sat
            - label: Sonntag
              value: sun

    # Profil 2
    trigger_time_2:
      name: Startzeit 2 (z.B. Wochenende)
      default: "09:00:00"
      selector:
        time: {}
    days_2:
      name: Tage für Startzeit 2
      description: "Wenn leer, ist dieses Profil deaktiviert."
      default: 
        - sat
        - sun
      selector:
        select:
          multiple: true
          options:
            - label: Montag
              value: mon
            - label: Dienstag
              value: tue
            - label: Mittwoch
              value: wed
            - label: Donnerstag
              value: thu
            - label: Freitag
              value: fri
            - label: Samstag
              value: sat
            - label: Sonntag
              value: sun

variables:
  total_duration: !input duration
  delay_seconds: "{{ total_duration | float / 50 }}"
  selected_color: !input light_color
  target_mireds: >
    {% if selected_color == 'Coolest (142 mired)' %}
      142
    {% elif selected_color == 'Cool (4000K)' %}
      250
    {% elif selected_color == 'Neutral (2700K)' %}
      370
    {% elif selected_color == 'Warm (2200K)' %}
      454
    {% else %}
      500
    {% endif %}

trigger:
  - platform: time
    at: !input trigger_time_1
    id: "t1"
  - platform: time
    at: !input trigger_time_2
    id: "t2"

condition:
  - condition: or
    conditions:
      # Profil 1 Bedingung
      - condition: and
        conditions:
          - condition: trigger
            id: "t1"
          - condition: time
            weekday: !input days_1
      # Profil 2 Bedingung
      - condition: and
        conditions:
          - condition: trigger
            id: "t2"
          - condition: time
            weekday: !input days_2

action:
  - service: light.turn_on
    target:
      entity_id: !input target_light
    data:
      brightness_pct: 1
      color_temp: "{{ target_mireds }}"
      transition: 0

  - repeat:
      count: 50
      sequence:
        - delay:
            seconds: "{{ delay_seconds }}"
        - service: light.turn_on
          target:
            entity_id: !input target_light
          data:
            brightness_pct: "{{ repeat.index * 2 }}"
            color_temp: "{{ target_mireds }}"
            transition: 0